### ISSUE TITLE
import log fails in recent keystone vesions

### ISSUE THREAD

**Issue by giuliopaci** [telefonicaid/fiware-keystone-scim#15]
In recent versions of Keystone (e.g.: the one shipped with Debian testing), log is imported by oslo_log and not keystone.openstack.

Attached is a patch that solve the issue for me:
https://gist.github.com/giuliopaci/cdb18e75b260a4ac2d99

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/fiware-keystone-scim/pull/8
