### ISSUE TITLE
RPM Compatible with mitaka version

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-scim#43]
To be compatible with Keystone mitaka version RPM must have into account that https://github.com/telefonicaid/fiware-keystone-scim/blob/master/keystone-scim.spec#L23 file is in /etc/keystone/keystone-paste.ini instead of /usr/share/keystone/keystone-paste-dist.ini

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-keystone-scim/pull/44/
