### ISSUE TITLE
bug in pagination

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-scim#51]
users are paginated in a wrong way.

If I create 18 users like:
user1... user18 and then I try to list then I see:

keystone scim API: "GET /v3/OS-SCIM/Users?domain_id=2d11ea01a00c423b919cb336adb99c76&startIndex=0&count=15"

Keystone scim API: GET /v3/OS-SCIM/Users?domain_id=2d11ea01a00c423b919cb336adb99c76&startIndex=15&count=15

So its seems a keystone-scim bug/issue https://github.com/telefonicaid/fiware-keystone-scim

**Comment by fgalan** [comment]
Fixed by PR #50
