### ISSUE TITLE
error when name is not a column (limit decorator  is forcing sort by name )

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/fiware-keystone-scim#58]
introduced by https://github.com/telefonicaid/fiware-keystone-scim/pull/50

 a bug for keystone Newton and upper versions, since some tables like service does not have name as a column, an then query is not able to work

**Comment by AlvaroVega** [comment]
Newton and upper versions, at bootstraping are filling elements in service table, but service table does not have `name`  column

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/fiware-keystone-scim/pull/59
